# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:14
    restart: always
    container_name: culero-psql-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: culero
    networks:
      - culero-dev
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    container_name: culero-redis-dev
    ports:
      - '6379:6379'
    networks:
      - culero-dev
    volumes:
      - ./data/redis:/data

networks:
  culero-dev:
    driver: bridge
