# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:14
    restart: always
    container_name: culero-psql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: culero
    networks:
      - culero-dev
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    container_name: culero-redis
    ports:
      - '6379:6379'
    networks:
      - culero-dev
    volumes:
      - cache-data:/data

networks:
  culero-dev:
    driver: bridge

volumes:
  db-data:
    driver: local
  cache-data:
    driver: local
