primary_region = "syd"

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    soft_limit = 500
    hard_limit = 750

[http_service.tls_options]
  alpn = ["h2", "http/1.1"]
  versions = ["TLSv1.2", "TLSv1.3"]
  default_self_signed = true

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/api/health"
  protocol = "http"
  port = 4200
  tls_skip_verify = true

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpus = 1
  cpu_kind = "shared"
