name: CI

on:
  push:
    branches:
      - '!main'
      - '!develop'
      - '*'
    paths: ['apps/api/**']
  pull_request:
    paths: ['apps/api/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: ./backend
        run: pnpm install
      - name: Run Prettier (Pre-commit or in workflow)
        working-directory: ./backend
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: ./backend
        run: pnpm install
      - name: Run ESLint
        working-directory: ./backend
        run: pnpm lint
      - name: Run unit tests
        working-directory: ./backend
        run: pnpm run test:unit
      - name: Run e2e tests
        working-directory: ./backend
        run: pnpm run test:e2e
